### PR TITLE
add Chinese simplified

### PR DESCRIPTION
**Pull request by voisen**

### CODE REVIEW

**Comment by hackiftekhar** [comment]
@voisen can you also localize App Store related thing found in github? I''ll put that localization text on iTunesconnect before submitting next version.

**Comment by voisen** [comment]
You can give to the translated text to send to me, I help you to translate in Chinese language to give it to you.
你可以把要翻译的文本发送给我, 我帮你用中国的语言来翻译给你.

**Comment by hackiftekhar** [comment]
It's already in Localizable.strings file. You'll find all text at the bottom. They are commented texts. For example see here:-
https://github.com/voisen/IQScreenRuler/blob/bd4d1fdd170b2dad0c581d50fc4fbdf5c3c9c37e/ScreenRuler/zh-Hant.lproj/Localizable.strings#L131

**Comment by voisen** [comment]
This : ?


HOW IT WORKS:
 Step1: Take Screenshot of the app to debug it. This will automatically be saved to your Camera Roll -> Screenshots album.
 Step2: Open Screen Ruler app and you can see your recent screenshot, enable ruler and straight line frame.
 Step3: Check your screenshot dimensions and UI element positions by zooming in/out and using rulers and line frame.
 
 Other fantastic features of Ruler app:
 - 4 Sided dynamic ruler. You can also adjust ruler position using your finger. Long tap for more options.
 - Free hand ruler scale. It can also rotate to check angles.
 - Straighten line frame.
 - Long tap & move on screenshot to show RGB color values of any position.
 - Multi-feature crop too.
 - Change Aspect Ratio.
 - Screenshot Resizing.
 - Change Device Scale Factor.
 - Double-Tap, Pan, pinch gestures to zoom and move pictures.
 
 Download to see how QA engineers accelerating their business by reducing time to check pixel measurements.
 ******************************************
 //App Store Keywords
 
 Screenshot, ruler, scale, straighten, developer, QA, Quality Assurance

**Comment by hackiftekhar** [comment]
Yup, all those commented text. You can see some examples here:-
https://github.com/toioski/IQScreenRuler/blob/f2ebcd77dd2ac9b35110f0403e1da0d93bd1ce5e/ScreenRuler/it.lproj/Localizable.strings
https://github.com/aposnov/IQScreenRuler/blob/3e56acdc43da15ae4a20470765492edd2a4c18fb/ScreenRuler/ru.lproj/_Localizable.strings

**Comment by voisen** [comment]
Ok, I know, I was localized into Chinese

**Comment by voisen** [comment]
Hello, I have submitted a new pull-request, see whether that is.

**Pull request merged**
